# Generated by Django 6.0 on 2025-12-13 12:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=200, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('sent_date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-sent_date'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('title', models.CharField(max_length=200, verbose_name='Titre professionnel')),
                ('bio', models.TextField(verbose_name='Biographie')),
                ('profile_picture', models.ImageField(upload_to='profile/', verbose_name='Photo de profil')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('github_link', models.URLField(blank=True, null=True, verbose_name='Lien GitHub')),
                ('linkedin_link', models.URLField(blank=True, null=True, verbose_name='Lien LinkedIn')),
                ('twitter_link', models.URLField(blank=True, null=True, verbose_name='Lien Twitter')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cv/', verbose_name='Fichier CV')),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profils',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.CharField(max_length=300, verbose_name='Description courte')),
                ('detailed_description', models.TextField(verbose_name='Description détaillée')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Image du projet')),
                ('technologies', models.CharField(max_length=300, verbose_name='Technologies')),
                ('project_url', models.URLField(blank=True, null=True, verbose_name='Lien du projet')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='Lien GitHub')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('is_featured', models.BooleanField(default=True, verbose_name='Projet mis en avant')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la compétence')),
                ('category', models.CharField(max_length=100, verbose_name='Catégorie')),
                ('level', models.IntegerField(default=50, verbose_name='Niveau (%)')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Icône')),
            ],
            options={
                'verbose_name': 'Compétence',
                'verbose_name_plural': 'Compétences',
                'ordering': ['category', 'name'],
            },
        ),
    ]
